application: thought-jot
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: true


handlers:

# ndb_users
- url: /_login/assets
  static_dir: ndb_users/assets
- url: /_login(.*)
  script: ndb_users.login.app
  secure: always
- url: /_ah/bounce
  script: ndb_users.mail.app
  login: admin

# API requests
- url: /api/.*
  script: api.app
  secure: always

# Static files
- url: /(.*\.(gif|png|jpg|css|js|html))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|css|js|html)$

# AngularJS app stub
- url: /.*
  static_files: static/app.html
  upload: static/app.html
  secure: always


libraries:
- name: webapp2
  version: latest

inbound_services:
- mail_bounce